### Signin
POST http://localhost:8080/api/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "test@example.com",
    "password": "MySecurePassword"
}


### Signup

POST http://localhost:8080/api/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "test@example.com",
    "password": "MySecurePassword",
    "passwordConfirm": "MySecurePassword",
    "phone": "+919999999999",
    "name": "Test User"
}