### Create a new Project

POST http://localhost:8080/api/project HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmY2Y2MwOTgyZWE3NTA3Y2ZkYjRlMCIsImlhdCI6MTYxNzk0NjUwNSwiZXhwIjoxNjE3OTUwMTA1fQ.QNN-XgY1sHrecmW9GjAQXIvZ2SwcCD-ySIulkVDz6es

{
    "title": "This is Cool Title",
    "description": "This is my Cool Project Description",
    "postedBy": "606c2d8e431ce145e8027aab"
}

# title: String
# description: String
# postedBy: orgId


### Get all projects

GET http://localhost:8080/api/project HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmY2Y2MwOTgyZWE3NTA3Y2ZkYjRlMCIsImlhdCI6MTYxNzk0NjUwNSwiZXhwIjoxNjE3OTUwMTA1fQ.QNN-XgY1sHrecmW9GjAQXIvZ2SwcCD-ySIulkVDz6es



### Get Projects Org Wise

# http://localhost:8080/api/project/:orgId

GET http://localhost:8080/api/project/606c2d8e431ce145e8027aab HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmY2Y2MwOTgyZWE3NTA3Y2ZkYjRlMCIsImlhdCI6MTYxNzk0NjUwNSwiZXhwIjoxNjE3OTUwMTA1fQ.QNN-XgY1sHrecmW9GjAQXIvZ2SwcCD-ySIulkVDz6es



### Update Project

# http://localhost:8080/api/project/:projectId
PUT http://localhost:8080/api/project/606fe905aad9182788c2b63b HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmY2Y2MwOTgyZWE3NTA3Y2ZkYjRlMCIsImlhdCI6MTYxNzk0NjUwNSwiZXhwIjoxNjE3OTUwMTA1fQ.QNN-XgY1sHrecmW9GjAQXIvZ2SwcCD-ySIulkVDz6es

{
    "title": "This is New Title",
    "description": "This is the new description"
}


### Delete Project

# http://localhost:8080/api/project/:projectId
DELETE http://localhost:8080/api/project/606fe905aad9182788c2b63b HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmY2Y2MwOTgyZWE3NTA3Y2ZkYjRlMCIsImlhdCI6MTYxNzk0NjUwNSwiZXhwIjoxNjE3OTUwMTA1fQ.QNN-XgY1sHrecmW9GjAQXIvZ2SwcCD-ySIulkVDz6es