### Create a new Project

POST http://localhost:8080/api/project HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWM1NTA0OWQ3ZDY3M2EyMDIwMmVkNSIsImlhdCI6MTYxNzcwMTYzMSwiZXhwIjoxNjE3NzA1MjMxfQ.txTdjktGax6oDezdoehmCDjGCrkU2AH8rH_NQaZmadk

{
    "title": "This is Cool Title",
    "description": "This is my Cool Project Description",
    "postedBy": "606c2d8e431ce145e8027aab"
}

# title: String
# description: String
# postedBy: orgId


### Get all projects

GET http://localhost:8080/api/project HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWM1NTA0OWQ3ZDY3M2EyMDIwMmVkNSIsImlhdCI6MTYxNzcwMTYzMSwiZXhwIjoxNjE3NzA1MjMxfQ.txTdjktGax6oDezdoehmCDjGCrkU2AH8rH_NQaZmadk



### Get Projects Org Wise

# http://localhost:8080/api/project/:orgId

GET http://localhost:8080/api/project/606c2d8e431ce145e8027aab HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWM1NTA0OWQ3ZDY3M2EyMDIwMmVkNSIsImlhdCI6MTYxNzcwMTYzMSwiZXhwIjoxNjE3NzA1MjMxfQ.txTdjktGax6oDezdoehmCDjGCrkU2AH8rH_NQaZmadk



### Update Project

# http://localhost:8080/api/project/:projectId
PUT http://localhost:8080/api/project/606c3f6be4f97e32680e0dfe HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWM1NTA0OWQ3ZDY3M2EyMDIwMmVkNSIsImlhdCI6MTYxNzcwMTYzMSwiZXhwIjoxNjE3NzA1MjMxfQ.txTdjktGax6oDezdoehmCDjGCrkU2AH8rH_NQaZmadk

{
    "title": "This is New Title",
    "description": "This is the new description"
}


### Delete Project

# http://localhost:8080/api/project/:projectId
DELETE http://localhost:8080/api/project/606c3f6be4f97e32680e0dfe HTTP/1.1
content-type: application/json
cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNWM1NTA0OWQ3ZDY3M2EyMDIwMmVkNSIsImlhdCI6MTYxNzcwMTYzMSwiZXhwIjoxNjE3NzA1MjMxfQ.txTdjktGax6oDezdoehmCDjGCrkU2AH8rH_NQaZmadk