name: api tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Run Test Cases
        env:
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: |
          cd fb-phase2-backend && ls
          yarn
          echo "DATABASE_URI=$DATABASE_URI" > .env
          yarn test
